[SERVICE]
    Flush         2
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name              tail
    Path              /logs/app.log
    Parser            json
    Tag               app.logs
    Refresh_Interval  5
    Mem_Buf_Limit     5MB

[INPUT]
    Name              docker
    Tag               docker.*
    Unix_Path         /var/run/docker.sock
    Buffer_Size       8192
    Parser            docker

# FILTER 1: Enrich app logs
[FILTER]
    Name          record_modifier
    Match         app.logs
    Record        host    fluent-bit-demo
    Record        env     production
    Record        source  file-tail

# FILTER 2: Enrich docker logs
[FILTER]
    Name          record_modifier
    Match         docker.*
    Record        source  docker-socket
    Record        env     production

# FILTER 3: Drop Fluent Bit's own noisy internal logs
[FILTER]
    Name    grep
    Match   docker.*
    Exclude log .*fluent-bit.*

# OUTPUT 1: App logs -> ES index: fluent-bit-app 
[OUTPUT]
    Name               es
    Match              app.logs
    Host               elasticsearch
    Port               9200
    Index              fluent-bit-app
    Suppress_Type_Name On
    tls                Off

# OUTPUT 2: Docker logs -> ES index: fluent-bit-docker 
[OUTPUT]
    Name               es
    Match              docker.*
    Host               elasticsearch
    Port               9200
    Index              fluent-bit-docker
    Suppress_Type_Name On
    tls                Off

# OUTPUT 3: stdout - watch live with: docker logs -f fluent-bit
[OUTPUT]
    Name    stdout
    Match   *
    Format  json_lines
