[SERVICE]
    Flush         2
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name          tail
    Path          /logs/app.log
    Parser        json
    Tag           app.logs
    Refresh_Interval 5
    Mem_Buf_Limit 5MB

[FILTER]
    Name          record_modifier
    Match         app.logs
    Record        host fluent-bit-demo
    Record        env  production

[OUTPUT]
    Name          es
    Match         app.logs
    Host          elasticsearch
    Port          9200
    Index         fluent-bit-logs
    Suppress_Type_Name On
    tls           Off

[OUTPUT]
    Name          stdout
    Match         app.logs
    Format        json_lines
